In [31]:
!pip3 install torch
import torch
from torch.nn import Linear #we will use inheritance such that LR will leverage base class nn.Module

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [32]:
w = torch.tensor(3.0, requires_grad=True) #3 is a random value for weight, #slope
b = torch.tensor(1.0, requires_grad=True) #y-intercept
#x #weight 
#y=w*x+b




In [33]:
def forward(x): #Forward function, receives the input (x value), which will be passed into model
  y=w*x +b
  return y

In [34]:
x = torch.tensor([[2], [7]])
forward(x)
#Prediction of 7 and 22 here.

tensor([[ 7.],
        [22.]], grad_fn=<AddBackward0>)

In [35]:
import tensorflow as tf
torch.manual_seed(1) #Generate random numbers
model = Linear(in_features=1, out_features=1) #For every prediction, for every output, there is a single input
print(model.bias, model.weight)
#y = 0.5153x - 0.4414

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [36]:
x = torch.tensor([2.0]) #float value 
model(x)
#y = 0.5891 when x = 2.0

tensor([0.5891], grad_fn=<AddBackward0>)